# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files (x86)\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files (x86)\CMake\bin\cmake.exe" -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = D:\git\libsat

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = D:\git\libsat

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"C:\Program Files (x86)\CMake\bin\cmake-gui.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:\Program Files (x86)\CMake\bin\cmake.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start D:\git\libsat\CMakeFiles D:\git\libsat\CMakeFiles\progress.marks
	$(MAKE) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start D:\git\libsat\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sat

# Build rule for target.
sat: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 sat
.PHONY : sat

# fast build rule for target.
sat/fast:
	$(MAKE) -f CMakeFiles\sat.dir\build.make CMakeFiles/sat.dir/build
.PHONY : sat/fast

libsat.obj: libsat.cpp.obj

.PHONY : libsat.obj

# target to build an object file
libsat.cpp.obj:
	$(MAKE) -f CMakeFiles\sat.dir\build.make CMakeFiles/sat.dir/libsat.cpp.obj
.PHONY : libsat.cpp.obj

libsat.i: libsat.cpp.i

.PHONY : libsat.i

# target to preprocess a source file
libsat.cpp.i:
	$(MAKE) -f CMakeFiles\sat.dir\build.make CMakeFiles/sat.dir/libsat.cpp.i
.PHONY : libsat.cpp.i

libsat.s: libsat.cpp.s

.PHONY : libsat.s

# target to generate assembly for a file
libsat.cpp.s:
	$(MAKE) -f CMakeFiles\sat.dir\build.make CMakeFiles/sat.dir/libsat.cpp.s
.PHONY : libsat.cpp.s

satbox.obj: satbox.cpp.obj

.PHONY : satbox.obj

# target to build an object file
satbox.cpp.obj:
	$(MAKE) -f CMakeFiles\sat.dir\build.make CMakeFiles/sat.dir/satbox.cpp.obj
.PHONY : satbox.cpp.obj

satbox.i: satbox.cpp.i

.PHONY : satbox.i

# target to preprocess a source file
satbox.cpp.i:
	$(MAKE) -f CMakeFiles\sat.dir\build.make CMakeFiles/sat.dir/satbox.cpp.i
.PHONY : satbox.cpp.i

satbox.s: satbox.cpp.s

.PHONY : satbox.s

# target to generate assembly for a file
satbox.cpp.s:
	$(MAKE) -f CMakeFiles\sat.dir\build.make CMakeFiles/sat.dir/satbox.cpp.s
.PHONY : satbox.cpp.s

satcircle.obj: satcircle.cpp.obj

.PHONY : satcircle.obj

# target to build an object file
satcircle.cpp.obj:
	$(MAKE) -f CMakeFiles\sat.dir\build.make CMakeFiles/sat.dir/satcircle.cpp.obj
.PHONY : satcircle.cpp.obj

satcircle.i: satcircle.cpp.i

.PHONY : satcircle.i

# target to preprocess a source file
satcircle.cpp.i:
	$(MAKE) -f CMakeFiles\sat.dir\build.make CMakeFiles/sat.dir/satcircle.cpp.i
.PHONY : satcircle.cpp.i

satcircle.s: satcircle.cpp.s

.PHONY : satcircle.s

# target to generate assembly for a file
satcircle.cpp.s:
	$(MAKE) -f CMakeFiles\sat.dir\build.make CMakeFiles/sat.dir/satcircle.cpp.s
.PHONY : satcircle.cpp.s

satpolygon.obj: satpolygon.cpp.obj

.PHONY : satpolygon.obj

# target to build an object file
satpolygon.cpp.obj:
	$(MAKE) -f CMakeFiles\sat.dir\build.make CMakeFiles/sat.dir/satpolygon.cpp.obj
.PHONY : satpolygon.cpp.obj

satpolygon.i: satpolygon.cpp.i

.PHONY : satpolygon.i

# target to preprocess a source file
satpolygon.cpp.i:
	$(MAKE) -f CMakeFiles\sat.dir\build.make CMakeFiles/sat.dir/satpolygon.cpp.i
.PHONY : satpolygon.cpp.i

satpolygon.s: satpolygon.cpp.s

.PHONY : satpolygon.s

# target to generate assembly for a file
satpolygon.cpp.s:
	$(MAKE) -f CMakeFiles\sat.dir\build.make CMakeFiles/sat.dir/satpolygon.cpp.s
.PHONY : satpolygon.cpp.s

satvector.obj: satvector.cpp.obj

.PHONY : satvector.obj

# target to build an object file
satvector.cpp.obj:
	$(MAKE) -f CMakeFiles\sat.dir\build.make CMakeFiles/sat.dir/satvector.cpp.obj
.PHONY : satvector.cpp.obj

satvector.i: satvector.cpp.i

.PHONY : satvector.i

# target to preprocess a source file
satvector.cpp.i:
	$(MAKE) -f CMakeFiles\sat.dir\build.make CMakeFiles/sat.dir/satvector.cpp.i
.PHONY : satvector.cpp.i

satvector.s: satvector.cpp.s

.PHONY : satvector.s

# target to generate assembly for a file
satvector.cpp.s:
	$(MAKE) -f CMakeFiles\sat.dir\build.make CMakeFiles/sat.dir/satvector.cpp.s
.PHONY : satvector.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... sat
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... libsat.obj
	@echo ... libsat.i
	@echo ... libsat.s
	@echo ... satbox.obj
	@echo ... satbox.i
	@echo ... satbox.s
	@echo ... satcircle.obj
	@echo ... satcircle.i
	@echo ... satcircle.s
	@echo ... satpolygon.obj
	@echo ... satpolygon.i
	@echo ... satpolygon.s
	@echo ... satvector.obj
	@echo ... satvector.i
	@echo ... satvector.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

